spring:
  profiles:
    default: local
  application:
    name: hrmapp-backend-api


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    issuer: hrmapp
    access-token-expiration-minutes: 60
    refresh-token-expiration-days: 30
    secret: HRMAPP_DEMO_SECRET_KEY_CHANGE_IN_PRODUCTION_1234567890
  storage:
    container-name: hrmapp-files